### ISSUE TITLE
誰でも(ログインをしていなくても) Admin 機能が使え、例えば shop を削除することが出来てしまう

### ISSUE THREAD

**Issue by kachick** [wa-r/SWEETS_meguri#134]
http://sweets-meguri.work/admin/shops

<img width="1558" alt="スクリーンショット 2021-02-20 2 53 48" src="https://user-images.githubusercontent.com/1180335/108542422-0e8d6b80-7327-11eb-932c-1d288794dd32.png">

この画面に編集・削除ボタンが有り、削除を押したら実際消せてしまったのですが仕様でしょうか？

https://github.com/wa-r/SWEETS_meguri/blob/38c9761ecc4459def737f82d6d859eb80559a05c/app/controllers/admin/shops_controller.rb#L41-L45

この admin 周りの controller 系に 他で言う current_member 相当の認証ロジックが見当たらなかったので、それが理由かな？とは思いました。

**Comment by wa-r** [comment]
ご指摘をいただき、ありがとうございます。
こちらにつきましては、コントローラーに「before_action :authenticate_admin!」を、ビューには「if admin_signed_in? 」の記述を追加し対応致しました。seeds.rbに管理者側の情報が掲載、公開されてしまっているのは良くないかと思いますので、今後修正したいと思います。
※スクールでの課題により、現在の管理者情報で閲覧できるとスクールにお伝えしておりますので、総評をいただき次第訂正させていただこうと考えております。

**Comment by kachick** [comment]
了解しました、素早いご対応ありがとうございます！
