### ISSUE TITLE
seeds が公開されているため、生成されたユーザーでログインできてしまう

### ISSUE THREAD

**Issue by kachick** [wa-r/SWEETS_meguri#136]
https://github.com/wa-r/SWEETS_meguri/blob/38c9761ecc4459def737f82d6d859eb80559a05c/db/seeds.rb#L8-L62

<img width="1134" alt="スクリーンショット 2021-02-20 3 36 29" src="https://user-images.githubusercontent.com/1180335/108546818-ffa9b780-732c-11eb-87ea-783d8ae9e0e9.png">

https://github.com/SHOGOHORI/sukusuku_ver2/issues/115 の方も同じ状況でした。これはこれで気にしないということであれば良いと思います！ (Admin まで あるのは大丈夫かな？と思いましたが)

**Comment by wa-r** [comment]
@kachick 
ご指摘をいただき、ありがとうございます。
こちらの件に関しましては、特に大きな問題にはならないかと思いますので、今回はこのままとさせていただきたいと思います。

**Comment by kachick** [comment]
了解しました！
